version: '3.1'

services:
  db:
    container_name: kitten-database
    image: mysql:8.1
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - "./db/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: kitten_house
      MYSQL_USER: admin_kitten
      MYSQL_PASSWORD: kitten_pwd
    expose:
      - 3306
    ports:
      - 3306:3306
  
  migrations:
    container_name: kitten-migrations
    build:
      context: ./db/.
      dockerfile: ./Dockerfile
    environment:
      - DATABASE="mysql://admin_kitten:kitten_pwd@tcp(db:3306)/kitten_house"
  
  kitten_authenticator_svc:
    container_name: kitten-authenticator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: kitten_house
      MYSQL_USER: admin_kitten
      MYSQL_PASSWORD: kitten_pwd
    ports:
      - 8080:8080